import type { CatalogBook } from "@/lib/catalog-schema";

export function catalogBook(overrides: Partial<CatalogBook> = {}): CatalogBook {
  return {
    id: "book-1",
    assetId: "asset-1",
    recordNo: 1,
    title: "테스트 도서",
    subtitle: "",
    author: "정민제",
    publisher: "선비북스",
    category: "컴퓨터/IT",
    price: 9_900,
    fileFormat: "EPUB",
    saleStatus: "판매중",
    pdfIsbn: "",
    epubIsbn: "9791124700001",
    activeIsbn: "9791124700001",
    isbnStatus: "발급완료",
    publicationDate: "2026-07-01",
    registeredAt: "2026-07-01T00:00:00.000Z",
    kyoboProductCode: "kyobo-1",
    kyoboSalesProductId: "sales-1",
    salesChannelCode: "",
    b2bPurchaseStatus: "",
    b2bRentalStatus: "",
    samPremiumStatus: "",
    samUnlimitedStatus: "",
    final: true,
    cover: "cover.jpg",
    epub: "book.epub",
    pdf: "",
    manuscript: "",
    summary: "",
    platforms: {
      kyobo: "유통중",
      yes24: "유통중",
      ridi: "유통중",
      aladin: "유통중",
      millie: "유통중",
    },
    registeredCount: 5,
    missingPlatforms: [],
    attentionPlatforms: [],
    assetMatchMethod: "fixture",
    fivePlatformMatchMethod: "fixture",
    source: "ai-catalog",
    ...overrides,
  };
}
